### ISSUE TITLE
[BUG]  Latest image doesn't start

### ISSUE THREAD

**Issue by jokob-sk** [linuxserver/docker-filezilla#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Getting a BAD gateway 502 error

### Steps To Reproduce

1. Pulled the latest image and now the container is giving an NGINX 502 BAD gateway error

### Environment

```markdown
- OS:Synology
- How docker service was installed: Docker-compose
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "3"
services:
  filezilla:
    container_name: filezilla
#    image: "lscr.io/linuxserver/filezilla:latest"
    image: "linuxserver/filezilla
    network_mode: "bridge"
    restart: always
    ports:
      - "3774:3000" # host:container
      - "3773:3389" # host:container
      - "3775:3785" # host:container
      - "3779:3789" # host:container
    volumes:
      - ${BACKUP_LOCATION}/x_local/soft/favicons/filezilla/favicon.ico:/gclient/public/favicon.ico
      - ${BACKUP_LOCATION}/x_local/soft/favicons/filezilla/ms-icon-70x70.png:/gclient/public/icon.png
      - ${PLEX_LOCATION}/Plex:/mnt/Plex
      - ${APP_DATA_LOCATION}/filezilla/config:/config
      - ${APP_DATA_LOCATION}/filezilla/data:/data



```
```


### Container logs

```bash
filezilla    | Node.js v18.14.2
filezilla    | Home directory not accessible: Permission denied
filezilla    | node:events:491
filezilla    |       throw er; // Unhandled 'error' event
filezilla    |       ^
filezilla    |
filezilla    | Error: Access denied
filezilla    |     at /kclient/node_modules/pulseaudio2/lib/pulse.js:133:21
filezilla    |     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
filezilla    | Emitted 'error' event on Context instance at:
filezilla    |     at /kclient/node_modules/pulseaudio2/lib/pulse.js:135:22
filezilla    |     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

**Comment by jokob-sk** [comment]
FYI downgraded to `linuxserver/filezilla:3.59.0-r0-ls81` > this one works

**Comment by thelamer** [comment]
Remove the /config mount temporarily, you will lose your settings, but it looks like the app does not have permissions to create the pulseaudio pid for running audio.
I know audio on a filezilla container does not make a ton of sense, but these base images start a series of default services to accommodate a full desktop environment. 
From there I am not 100% I don't have Synology hardware, but I know they do some super weird stuff with their permission layout. A 777 chmod might be your only choice there, but again not sure.

**Comment by thelamer** [comment]
Can you please test the latest image and let me know if this is still occurring.

**Comment by jokob-sk** [comment]
Even when removing the config mapping:

```yaml
version: "3"
services:
  filezilla:
    container_name: filezilla
#    image: linuxserver/filezilla:3.59.0-r0-ls81
    image: linuxserver/filezilla:latest
    network_mode: "bridge"
    restart: always
    ports:
      - "3774:3000" # host:container
      - "3773:3389" # host:container
      - "3775:3785" # host:container
      - "3779:3789" # host:container
    volumes:
      - ${BACKUP_LOCATION}/x_local/soft/favicons/filezilla/favicon.ico:/gclient/public/favicon.ico
      - ${BACKUP_LOCATION}/x_local/soft/favicons/filezilla/ms-icon-70x70.png:/gclient/public/icon.png
      - ${PLEX_LOCATION}:/mnt/Plex
#      - ${APP_DATA_LOCATION}/filezilla/config:/config
#      - ${APP_DATA_LOCATION}/filezilla/data:/data  
```

Same error on latest image:

```

filezilla    |
filezilla    | Error: Access denied
filezilla    |     at /kclient/node_modules/pulseaudio2/lib/pulse.js:133:21
filezilla    |     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
filezilla    | Emitted 'error' event on Context instance at:
filezilla    |     at /kclient/node_modules/pulseaudio2/lib/pulse.js:135:22
filezilla    |     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
filezilla    |
filezilla    | Node.js v18.14.2
filezilla    | node:events:491
filezilla    |       throw er; // Unhandled 'error' event
filezilla    |       ^
filezilla    |
filezilla    | Error: Access denied
filezilla    |     at /kclient/node_modules/pulseaudio2/lib/pulse.js:133:21
filezilla    |     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
filezilla    | Emitted 'error' event on Context instance at:
filezilla    |     at /kclient/node_modules/pulseaudio2/lib/pulse.js:135:22
filezilla    |     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
filezilla    |
filezilla    | Node.js v18.14.2
filezilla    | node:events:491
filezilla    |       throw er; // Unhandled 'error' event
filezilla    |       ^
filezilla    |
filezilla    | Error: Access denied
filezilla    |     at /kclient/node_modules/pulseaudio2/lib/pulse.js:133:21
filezilla    |     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
filezilla    | Emitted 'error' event on Context instance at:

```
